### ISSUE TITLE
new lane wird nicht gesetzt

### ISSUE THREAD

**Issue by ghost** [Georggue/MagnetTrain#12]
könnte mit gravityumkehrung zusammenhängen wenn man stirbt oder so

**Comment by ghost** [comment]
![sdfsdfsf](https://cloud.githubusercontent.com/assets/18441668/15656768/cc4a9252-26aa-11e6-8fbd-eca77baf9ff1.jpg)

**Comment by Georggue** [comment]
keine Ahnung wann das passiert, ich krieg es ums verrecken nicht nachgestellt

**Comment by ghost** [comment]
ich leider auch nicht :(
