### ISSUE TITLE
Playermodels

### ISSUE THREAD

**Issue by ghost** [Georggue/MagnetTrain#14]
Wenn wir vom Namen von MagnetTrain auf MagnetHighway umstellen sollten wäre sowas doch n gutes Playermodell http://tf3dm.com/3d-model/wraith-raider-starship-22193.html

**Comment by Georggue** [comment]
Joa, das sieht ziemlich nice aus eigentlich.  Dazu ne hübsche Animation, dann würde das gut passen wenn wir den Rest ähnlich gestalten

**Comment by ghost** [comment]
http://www.sharecg.com/v/72093/related/5/3D-Model/HN48-Flying-Car
das hätte 33k polygone

**Comment by Georggue** [comment]
https://www.assetstore.unity3d.com/en/#!/content/19137 Den hier hätte ich noch gefunden ansonsten

**Comment by ghost** [comment]
joa auch net schlecht
